
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    tomcat:
      test-while-idle: true 
      validation-query: SELECT 1
  devtools:
    restart:
      enabled: true
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate.ddl-auto: none
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization: 
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  main.lazy-initialization: true
  messages:
    basename: i18n/messages,i18n/labels
    encoding: ISO-8859-1
  mvc.format:
    date: iso
    date-time: iso
    time: iso
  profiles:
    active:
      default
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  sql:
    init:
      continue-on-error: true
  
server: 
  port: 8080

springdoc.swagger-ui.path: /swagger-ui
